{"name": "Проверка, что при авторизации с неправильным паролем или логином, запрос возвращает ошибку", "status": "passed", "description": "Проверка статус кода = 404 и сообщения Учетная запись не найдена при неверном пароле курьера", "steps": [{"name": "Создание аккаунта курьера", "status": "passed", "start": 1721133148386, "stop": 1721133148571}, {"name": "Логин курьера в системе с неправильным логином", "status": "passed", "start": 1721133148571, "stop": 1721133148987}, {"name": "Проверка статус кода = 404 и сообщения \"Учетная запись не найдена\"", "status": "passed", "start": 1721133148987, "stop": 1721133148987}, {"name": "Логин курьера в системе с неправильным паролем", "status": "passed", "start": 1721133148987, "stop": 1721133149098}, {"name": "Проверка статус кода = 404 и сообщения \"Учетная запись не найдена\"", "status": "passed", "start": 1721133149098, "stop": 1721133149098}, {"name": "Удаление аккаунта курьера", "status": "passed", "start": 1721133149098, "stop": 1721133149353}], "start": 1721133148386, "stop": 1721133149353, "uuid": "6d2b491c-12db-4f94-8e1e-645f5fd2d93b", "historyId": "a0d0b194c6fe1a92d882514ee99c7373", "testCaseId": "a0d0b194c6fe1a92d882514ee99c7373", "fullName": "tests.test_courier_login.TestCourierLogin#test_invalid_login_or_password_failed", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "DESKTOP-DSB2CVA"}, {"name": "thread", "value": "9512-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}